### ISSUE TITLE
There should be no Use GUI option when the software is Velocity

### ISSUE THREAD

**Issue by DongShaoNB** [Oli-idk/EasyMC#111]
There should be no Use GUI option when the software is Velocity

**Comment by saboooor** [comment]
And pterodactyl as well, will fix

**Comment by bwmp** [comment]
This has been fixed

**Comment by DongShaoNB** [comment]
This issue still exists when selecting Velocity, which directly add --nogui

**Comment by DongShaoNB** [comment]
> This has been fixed

This issue still exists when selecting Velocity, which directly add --nogui

**Comment by SnowzNZ** [comment]
> > This has been fixed
> 
> This issue still exists when selecting Velocity, which directly add --nogui

![image](https://github.com/birdflop/web/assets/98007575/b94dba9c-3f52-4c42-adaa-854e1c6acf7a)

**Comment by bwmp** [comment]
will be fixed next time we merge dev into production

**Comment by SnowzNZ** [comment]
I thought this was already fixed?

**Comment by bwmp** [comment]
--nogui flag doesnt exist on certain server softwares

**Comment by SnowzNZ** [comment]
Oh well this issue was for GUI option not arg never mind
